# Generated by Django 6.0.2 on 2026-02-11 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdecks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='joined_decks', to=settings.AUTH_USER_MODEL),
        ),
    ]
