# Generated by Django 6.0.2 on 2026-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classdecks', '0003_module_modulefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulefile',
            name='converted_pdf',
            field=models.FileField(blank=True, null=True, upload_to='module_files/converted/'),
        ),
        migrations.AddField(
            model_name='modulefile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('ppt', 'PPT'), ('pdf', 'PDF')], max_length=15),
        ),
    ]
